environments:
  your-tenant-alias:
    values:
      - ../defaults/01_system.defaults.yaml
      - ../defaults/10_document_chat.defaults.yaml
      - ../defaults/50_confluence_connector.defaults.yaml
      - ./your-tenant-alias.yaml
---
releases:
  - name: confluence-connector
    chart: oci://ghcr.io/unique-ag/helm-charts/backend-service
    version: 1.3.2
    namespace: apps
    createNamespace: true
    wait: false
    values:
      -
        image:
          repository: ghcr.io/unique-ag/confluence-connector
          tag: {{ .Values.confluenceConnector.tenantReleaseOverrides.confluenceConnector | default .Values.confluenceConnector.defaultReleases.confluenceConnector }}
        replicaCount: {{ .Values.confluenceConnector | get "replicaCount" 1 }}
        tyk:
          enabled: false
        service:
          enabled: false
        env:
          APP_PORT: 8083
          CONFLUENCE_TOKENS_PER_MINUTE: {{ .Values.confluenceConnector.env.CONFLUENCE_TOKENS_PER_MINUTE }}
          CONFLUENCE_URL: {{ .Values.confluenceConnector.env.CONFLUENCE_URL }}
          CRON_SCHEDULE: "0 0 * * *"
          INGEST_SINGLE_LABEL: {{ .Values.confluenceConnector.env.INGEST_SINGLE_LABEL }}
          INGEST_ALL_LABEL: {{ .Values.confluenceConnector.env.INGEST_ALL_LABEL }}
          INGESTION_URL: http://node-ingestion.chat.svc.cluster.local:8091
          OAUTH_TOKEN_URL: https://{{ .Values.zitadel.hostName }}/oauth/v2/token
          PROJECT_ID: {{ .Values.zitadel.projectId }}
          TEST_MODE: {{ .Values.confluenceConnector.env.TEST_MODE }}
        envSecrets:
          CLIENT_ID: {{ .Values.confluenceConnector.secrets.CLIENT_ID | fetchSecretValue | quote }}
          CLIENT_SECRET: {{ .Values.confluenceConnector.secrets.CLIENT_SECRET | fetchSecretValue | quote }}
          CONFLUENCE_USERNAME: {{ .Values.confluenceConnector.secrets.CONFLUENCE_USERNAME | fetchSecretValue | quote }}
          CONFLUENCE_PASSWORD: {{ .Values.confluenceConnector.secrets.CONFLUENCE_PASSWORD | fetchSecretValue | quote }}
          CONFLUENCE_PAT: {{ .Values.confluenceConnector.secrets.CONFLUENCE_PAT | fetchSecretValue | quote }}