environments:
  crown-prod:
    values:
      - ../defaults/01_system.defaults.yaml
      - ../defaults/40_reranker.defaults.yaml
      - ./your-tenant-alias.yaml
---
releases:
  - name: assistants-reranker
    chart: ../../charts/ai-service
    namespace: chat
    wait: false
    values:
      -
        replicaCount: {{ .Values.reranker.assistantsReranker | get "replicaCount" 1 }}
        strategy:
          type: {{ .Values.reranker.assistantsReranker | get "strategy.type" "RollingUpdate" }}
        image:
          repository: uniquecr.azurecr.io/ai-service-assistants-reranker
          tag: {{ .Values.reranker._common.tenantReleaseOverrides.assistantsReranker | default .Values.reranker._common.defaultReleases.assistantsReranker }}
        imagePullSecrets:
          - name: image-pull-secret
        env:
          API_BASE: http://node-chat.chat.svc.cluster.local:8093/public
          GUNICORN_WORKERS: {{ .Values.reranker.assistantsReranker.env.GUNICORN_WORKERS }}
          GUNICORN_THREADS: {{ .Values.reranker.assistantsReranker.env.GUNICORN_THREADS }}
          RERANKER_MODEL: {{ .Values.reranker.assistantsReranker.env.RERANKER_MODEL }}
        resources:
          {{ .Values.reranker.assistantsReranker.resources | toYaml | nindent 10 }}
        eventBasedAutoscaling:
          enabled: false
        securityContext:
          {{ .Values.reranker._common.securityContext | toYaml | nindent 10 }}