host: tenantzone.unique.app
chat:
  _common:
    database:
      host: ref+azurekeyvault://your-vault-name/host
      port: ref+azurekeyvault://your-vault-name/port
      password: ref+azurekeyvault://your-vault-name/password
      username: ref+azurekeyvault://your-vault-name/username
    auditVolume:
      enabled: true
      resourceGroup: ref+azurekeyvault://your-vault-name/resource-group-name
      storageAccount: ref+azurekeyvault://your-vault-name/storage-account-name
    acr:
      username: ref+azurekeyvault://your-vault-name/manual-acr-image-pull-username
      password: ref+azurekeyvault://your-vault-name/manual-acr-image-pull-password
    tenantReleaseOverrides:
      nextChat:
      nextKnowledgeUpload:
      nextTheme:
      nextAdmin:
      nodeChat:
      nodeIngestion:
      nodeIngestionWorker:
      configurationBackend:
      nodeScopeManagement:
      backendServiceSpeech:
      assistantsCore:
      reflector:
      agenticIngestion:
  nextTheme:
    env:
      STATIC_THEME_COLORS: {"color-primary-cta": "#D63384", "color-primary-variant": "#B2447A", "color-secondary": "#042834", "color-secondary-variant": "#03212B", "color-background": "#F7F7F7", "color-background-variant": "#EBEBED", "color-surface": "#FFFFFF", "color-control": "#D8D8D8", "color-info": "#0A96E6", "color-success-light": "#A0C855", "color-success-dark": "#3D9E3F", "color-error-light": "#F65D67", "color-error-dark": "#DC3545", "color-attention": "#FFC65C", "color-attention-variant": "#19AADA", "color-on-primary": "#FFFFFF", "color-on-secondary": "#FFFFFF", "color-on-background-main": "#02161D", "color-on-background-dimmed": "#1F505F", "color-on-surface": "#02161D", "color-on-control-main": "#02161D", "color-on-control-dimmed": "#9C9C9C", "color-on-info": "#FFFFFF", "color-on-success-light": "#FFFFFF", "color-on-success-dark": "#FFFFFF", "color-on-error-light": "#FFFFFF", "color-on-error-dark": "#FFFFFF", "color-on-attention": "#02161D", "color-on-attention-variant": "#FFFFFF"}
      STATIC_BACKGROUND_COLOR: F7F7F7
      STATIC_TAB_NAME: "YOUR_TAB_NAME"
  configurationBackend:
    env:
      FEATURE_FLAG_ENABLE_MCP_UN_11963: "true" # experimental MCP feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MCP_ADMIN_UN_14099: "true" # experimental MCP admin feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MCP_TOOL_REFRESH_UN_19255: "true" # experimental MCP tool refresh button feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_SPACES_2_0_UN_11203: "true" # enable spaces 2.0, BETA feature
      FEATURE_FLAG_ENABLE_FILE_BASED_ACCESS_UN_12660: "false" # experimental file-based access feature, only enable for DEV/TEST
      FEATURE_FLAG_CONFIGURE_FILE_METADATA_UN_10908: "true" # enable file metadata configuration, BETA feature
      FEATURE_FLAG_ENABLE_HTML_RENDERING_UN_15131: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_DEEP_RESEARCH_UN_12630: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_THINKING_STEPS_UN_13848: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_CODE_EXECUTION_UN_17498: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_USE_OPENAI_V1_13819: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_NEW_ANSWERS_UI_UN_14411: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_NEW_ANSWER_FORMATTING_UN_14392: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MOVE_FILE_UN_15517: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MOVE_FOLDER_UN_16037: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MAGIC_TABLE_UN_8472: "true"
      FEATURE_FLAG_AGENTIC_TABLE_ERROR_BANNER_UN_11777: "true"
      FEATURE_FLAG_AGENTIC_TABLE_CONTEXT_UN_14904: "true"
      FEATURE_FLAG_AGENTIC_TABLE_SHEET_METADATA_UN_14904: "true"
      FEATURE_FLAG_AGENTIC_TABLE_ROW_METADATA_UN_14904: "true"
      FEATURE_FLAG_AGENTIC_TABLE_REFERENCE_SIDEBAR_COMPONENTS_UN_16483: "true"
      FEATURE_FLAG_ENABLE_SUB_AGENTS_UN_13661: "true"
      FEATURE_FLAG_ENABLE_END_USER_SPACE_UN_8855: "true"
      FEATURE_FLAG_SET_PRIVATE_FOLDER_ACCESS_DEFAULT_UN_13988: "true"
      FEATURE_FLAG_ENABLE_SESSION_TIMEOUT_UN_15656: "false" # Enables automatic session timeout after 30 minutes
      FEATURE_FLAG_ENABLE_AGENTIC_METADATA_EXTRACTION_UN_15619: "true" # Experimental feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_IMAGE_CONTENT_EXTRACTION_UN_17223: "true" # Experimental feature, only enable for DEV/TEST
  nodeChat:
    secrets:
      WORKLOAD_IDENTITY_CLIENT_ID: ref+azurekeyvault://your-vault-name/wid-client-id-node-chat
      AZURE_OPENAI_API_ENDPOINTS_JSON: ref+azurekeyvault://your-vault-name/azure-openai-endpoints-json
      AZURE_FGPT_STORAGE_CONNECTION_STRING: ref+azurekeyvault://your-vault-name/storage-account-connection-string-1
      CHAT_LXM_ENCRYPTION_KEY: ref+azurekeyvault://your-vault-name/chat-lxm-encryption-key
  nodeIngestion:
    secrets:
      AZURE_DOCUMENT_INTELLIGENCE_ENDPOINTS: ref+azurekeyvault://your-vault-name/azure-document-intelligence-endpoints
      AZURE_OPENAI_API_ENDPOINT: ref+azurekeyvault://your-vault-name/openai-endpoint
      AZURE_FGPT_STORAGE_CONNECTION_STRING: ref+azurekeyvault://your-vault-name/storage-account-connection-string-1
      AZURE_INGESTION_CACHE_STORAGE_CONNECTION_STRING: ref+azurekeyvault://your-vault-name/storage-account-connection-string-1
      WORKLOAD_IDENTITY_CLIENT_ID: ref+azurekeyvault://your-vault-name/wid-client-id-node-ingestion
      INGESTION_ENCRYPTION_KEY: ref+azurekeyvault://your-vault-name/ingestion-encryption-key
    env:
      ZITADEL_ROOT_ORG_ID: "<your-zitadel-root-org-id>"
  nodeIngestionWorker:
    secrets:
      WORKLOAD_IDENTITY_CLIENT_ID: ref+azurekeyvault://your-vault-name/wid-client-id-node-ingestion-worker
      AZURE_DOCUMENT_INTELLIGENCE_ENDPOINTS: ref+azurekeyvault://your-vault-name/azure-document-intelligence-endpoints
    env:
      CONVERT_OFFICE_FILES_TO_PDF: "true"
  nodeIngestionWorkerChat:
    secrets:
      WORKLOAD_IDENTITY_CLIENT_ID: ref+azurekeyvault://your-vault-name/wid-client-id-node-ingestion-worker-chat
  nodeScopeManagement:
    env:
      ZITADEL_ROOT_ORG_ID: "<your-zitadel-root-org-id>"
    extraRoutes:
      scim:
        hostnames:
          - <your-hostname> # backend hostname e.g.: api.your-hostname.com or gateway.your-hostname.com
      membership-sync:
        hostnames:
          - <your-hostname> # backend hostname e.g.: api.your-hostname.com or gateway.your-hostname.com
    secrets:
      SCOPE_MANAGEMENT_ENCRYPTION_KEY_1: ref+azurekeyvault://your-vault-name/scope-management-encryption-key-1
      SCOPE_MANAGEMENT_ENCRYPTION_KEY_2: ref+azurekeyvault://your-vault-name/scope-management-encryption-key-2
      ZITADEL_PAT: ref+azurekeyvault://your-vault-name/manual-zitadel-scope-mgmt-pat
  backendServiceSpeech:
    secrets:
      WORKLOAD_IDENTITY_CLIENT_ID: ref+azurekeyvault://your-vault-name/wid-client-id-backend-service-speech
      SPEECH_PRIVATE_ENDPOINT_HOST: ref+azurekeyvault://your-vault-name/switzerlandnorth-speech-fqdn
  assistantsCore:
    env:
      SIX_API_ACTIVATED_COMPANIES: '["<company_id>"]'
      FEATURE_FLAG_ENABLE_NEW_ANSWER_FORMATTING_UN_14392: "true" # Experimental feature, only enable for DEV/TEST
    envSecrets:
      AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT_DEFINITIONS: ref+azurekeyvault://your-vault-name/azure-document-intelligence-endpoint-definitions
      WORKLOAD_IDENTITY_CLIENT_ID: ref+azurekeyvault://your-vault-name/wid-client-id-assistants-core
      GOOGLE_SEARCH_API_KEY: ref+azurekeyvault://your-vault-name/manual-google-search-api-key
      SIX_API_CREDS: ref+azurekeyvault://your-vault-name/manual-six-api-creds
  agenticIngestion:
    secrets:
      WORKLOAD_IDENTITY_CLIENT_ID: ref+azurekeyvault://your-vault-name/wid-client-id-agentic-ingestion
      MDI_ENDPOINT_DEFINITIONS: ref+azurekeyvault://your-vault-name/azure-document-intelligence-endpoint-definitions
rabbitMQ:
  username: ref+azurekeyvault://your-vault-name/rabbitmq-username # ! can't be changed without deleting the PVC+PV
  password: ref+azurekeyvault://your-vault-name/rabbitmq-password # ! can't be changed without deleting the PVC+PV
  url: ref+azurekeyvault://your-vault-name/rabbitmq-url
  erlangCookie: ref+azurekeyvault://your-vault-name/rabbitmq-erlang-cookie # ! can't be changed without deleting the PVC+PV
  load_definition_policies: |-
    [
      {
        "vhost": "/",
        "name": "node-consumer-timeout",
        "pattern": "unique.node.ingestion.queue",
        "apply-to": "queues",
        "definition": {
          "consumer-timeout": 7200000
        },
        "priority": 1
      },
      {
        "vhost": "/",
        "name": "node-ingestion-timeout",
        "pattern": "unique.node.ingestion.queue",
        "apply-to": "queues",
        "definition": {
          "consumer-timeout": 7200000
        },
        "priority": 1
      },
      {
        "vhost": "/",
        "name": "node-ingestion-chat-timeout",
        "pattern": "unique.node.ingestion.chat_queue",
        "apply-to": "queues",
        "definition": {
          "consumer-timeout": 7200000
        },
        "priority": 1
      }
    ]
zitadel:
  orgId: "<your-zitadel-root-org-id>"
  projectId: "<your-zitadel-project-id>"
  clientId: "<your-zitadel-client-id>"
  hostName: id.tenantzone.unique.app # sub_domain created via TF
  mainKey: ref+azurekeyvault://your-vault-name/zitadel-main-key # ! can't be changed without deleting the PVC+PV
  database:
    host: ref+azurekeyvault://your-vault-name/host
    port: ref+azurekeyvault://your-vault-name/port
    username: ref+azurekeyvault://your-vault-name/username
    password: ref+azurekeyvault://your-vault-name/password
    zitadelPassword: ref+azurekeyvault://your-vault-name/zitadel-zitadel-password # ! can't be changed without deleting DB + ROLE
  theme:
    light:
      primary: D63384
      background: F7F7F7
      warn: F65D67
      font: 02161D
    dark:
      primary: D63384
      background: 02161D
      warn: F65D67
      font: F7F7F7
tyk:
  hostName: gateway.tenantzone.unique.app # sub_domain created via TF
  apiSecret: ref+azurekeyvault://your-vault-name/tyk-api-secret
  redis:
    host: ref+azurekeyvault://your-vault-name/redis-fqdn
    port: ref+azurekeyvault://your-vault-name/redis-port
    password: ref+azurekeyvault://your-vault-name/redis-password
appRepo:
  _common:
    database:
      host: ref+azurekeyvault://your-vault-name/host
      port: ref+azurekeyvault://your-vault-name/port
      password: ref+azurekeyvault://your-vault-name/password
      username: ref+azurekeyvault://your-vault-name/username
    auditVolume:
      enabled: true
      resourceGroup: ref+azurekeyvault://your-vault-name/resource-group-name
      storageAccount: ref+azurekeyvault://your-vault-name/storage-account-name
    acr:
      username: ref+azurekeyvault://your-vault-name/manual-acr-image-pull-username
      password: ref+azurekeyvault://your-vault-name/manual-acr-image-pull-password
    tenantReleaseOverrides:
      nodeAppRepository:
      nodeWebhookWorker:
      nodeWebhookScheduler:
      typescriptServiceEventSocket:
      clientInsightsExporter:
  nodeAppRepository:
    secrets:
      ENCRYPTION_KEY: ref+azurekeyvault://your-vault-name/manual-app-repository-encryption-key
confluenceConnector:
  tenantReleaseOverrides:
    confluenceConnector:
  env:
    UNIQUE_SCOPE_ID: "" # optional, if not set a scope is automatically created for every Confluence Space
  secrets:
    ZITADEL_CLIENT_ID: ref+azurekeyvault://your-vault-name/manual-confluence-connector-service-user-client-id
    ZITADEL_CLIENT_SECRET: ref+azurekeyvault://your-vault-name/manual-confluence-connector-service-user-client-secret
    CONFLUENCE_USERNAME: ref+azurekeyvault://your-vault-name/manual-confluence-connector-username
    CONFLUENCE_PASSWORD: ref+azurekeyvault://your-vault-name/manual-confluence-connector-password
    CONFLUENCE_PAT: ref+azurekeyvault://your-vault-name/manual-confluence-connector-pat
sharepointConnector:
  secrets:
    UNIQUE_ZITADEL_CLIENT_SECRET: ref+azurekeyvault://your-vault-name/manual-spc-zitadel-client-secret 
    KEY_PEM: ref+azurekeyvault://your-vault-name/manual-spc-certificate-private-key 
  connector:
    serviceAccount:
      workloadIdentity:
        clientId: <app-registration-client-id>
  connectorConfig:
    sharepoint:
      tenantId: <your-tenant-id>
      auth:
        clientId: <your-app-registration-client-id>
        thumbprintSha1: <your-certificate-thumbprint-sha1>
      sites:
      - siteId: 00000000-0000-0000-0000-000000000000
        syncColumnName: <your-sharepoint-sync-column-name>
        ingestionMode: recursive
        scopeId: scope_example123456789
        maxFilesToIngest: 10000
        storeInternally: enabled
        syncStatus: active
        syncMode: content_only
        # -- THIS CONFIG HAS EFFECT ONLY IN CONTENT_ONLY SYNC MODE: inheritance mode for scopes and files.
        # Allowed values: inherit_scopes_and_files, inherit_scopes, inherit_files, none.
        # When unset, defaults to inherit_scopes_and_files; ignored in content_and_permissions.
        permissionsInheritanceMode: inherit_scopes_and_files
        # -- Whether to recursively discover and sync content from subsites.
        # Allowed values: enabled, disabled. Default: disabled.
        subsitesScan: disabled
      - siteId: 00000000-0000-0000-0000-000000000001
        syncColumnName: <your-sharepoint-sync-column-name>
        ingestionMode: recursive
        scopeId: scope_example123456789
        maxFilesToIngest: 10000
        storeInternally: enabled
        syncStatus: active
        syncMode: content_only
        permissionsInheritanceMode: inherit_scopes_and_files
        subsitesScan: disabled
    unique:
      serviceExtraHeaders:
        x-company-id: "<your-zitadel-company-id>"
        x-user-id: "<your-zitadel-service-user-id>"
    processing:
      scanIntervalCron: "*/15 * * * *"
elasticsearch:
  ingestion:
    nodeSets:
      count: 3 # In production, run cluster with 3 nodes, can be set to 1 for development envs