apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-env
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  VERSION: "{{ .Values.image.tag }}"
  PORT: "{{ .Values.service.port }}"
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
