{{- if .Values.hooks.migration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backendService.fullname" . }}-migration-env
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "4"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  VERSION: "{{ .Values.image.tag }}"
  {{- if .Values.service.enabled }}
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}