{{- if and .Values.secretProvider .Values.hooks.migration.enabled }}
{{- $tenantId := .Values.secretProvider.tenantId | required ".Values.secretProvider.tenantId is required." -}}
{{- $fullName := include "backendService.fullname" . -}}
{{- $labels := include "backendService.mutableLabels" . -}}

{{- $usePodIdentity := "true" -}}
{{- $useVMManagedIdentity := "false" -}}
{{- $userAssignedIdentityID := "" -}}

{{- if .Values.secretProvider.useVMManagedIdentity }}
  {{- if and (eq .Values.secretProvider.useVMManagedIdentity "true") (ne .Values.secretProvider.userAssignedIdentityID "") }}
    {{- $usePodIdentity = "false" -}}
    {{- $useVMManagedIdentity = "true" -}}
    {{- $userAssignedIdentityID = .Values.secretProvider.userAssignedIdentityID | quote -}}
  {{- end }}
{{- end }}

{{- range $k, $v := .Values.secretProvider.vaults }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $fullName }}-{{ $k }}-migration
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  provider: azure
  secretObjects:
    - secretName: {{ $fullName }}-{{ $k }}
      labels:
        {{- $labels | nindent 8 }}
      data:
        {{- range $value := $v }}
        - key: {{ $value }}
          objectName: {{ $value }}
        {{- end }}
      type: Opaque
  parameters:
    usePodIdentity: {{ $usePodIdentity | quote }}
    useVMManagedIdentity: {{ $useVMManagedIdentity | quote }}
    userAssignedIdentityID: {{ $userAssignedIdentityID }}
    keyvaultName: {{ $k }}
    objects: |
      array:
        {{- range $value := $v }}
        - |
          objectName: {{ $value }}
          objectType: secret
        {{- end }}
    tenantId: {{ $tenantId }}
{{- end }}
{{- end }}