{{- if and .Values.envSecrets .Values.hooks.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backendService.fullname" . }}-migration-secrets
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
