{{- if and .Values.serviceAccount.enabled .Values.hooks.migration.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backendService.serviceAccountName" . }}-migration
  labels:
    {{- include "backendService.mutableLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    # we need to install the service account before the hooks, otherwise it can not be used
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
  {{- if .Values.serviceAccount.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentity.clientId }}
  {{- end }}
{{- end }}
