{{- if .Values.ingress.enabled -}}
{{- $fullName := include "backendService.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hosts := .Values.ingress.hosts -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ default "letsencrypt" .Values.ingress.clusterIssuer }}
    external-dns.alpha.kubernetes.io/hostname: {{ (index $hosts 0).host | quote }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}