{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backendService.fullname" . }}-secrets
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "backendService.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
