{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backendService.serviceAccountName" . }}
  labels:
    {{- include "backendService.mutableLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentity.clientId }}
  {{- end }}
{{- end }}
