{{- $fullName := include "common.fullname" . -}}
{{- range $val := .Values.spc }}
{{- if $val.install }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider: "azure"
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: {{ $val.useVMManagedIdentity | quote }}
    userAssignedIdentityID: {{ $val.userAssignedIdentityID | quote }}
    keyvaultName: {{ $val.keyvaultName | quote }}
    tenantId: {{ $val.tenantId | quote }}
    objects: {{ printf " |" }}

      array:

        {{- range $val_array := $.Values.spc }}
          {{- range $val_array_sec := $val_array.secrets }}
            {{- range $val_array_data := $val_array_sec.data }}
            {{- if eq  $val.name $val_array.name -}}

        {{ printf "" | indent 2 }}
        {{ printf "- |" | indent 2 }}

        {{ printf "objectName: %s" $val_array_data.objectName        | indent 4 }}
        {{ printf "objectType: %s" $val_array_data.objectType        | indent 4 }}
        {{ printf "objectVersion: %s" ($val_array_data.objectVersion | quote ) | indent 4 }}

            {{ end -}}

            {{- end }}
          {{- end }}
        {{- end }}

  secretObjects:
    {{- range $val_sec := $val.secrets }}
    - secretName: {{ $val_sec.name }}
      type: {{ $val_sec.type }}
      labels:
        creator: "{{ $fullName }}"
        SecretProviderCalss: {{ $val.name }}
        {{ range $key, $value := $val_sec.labels }}
          {{- $key }} : {{ $value }}
        {{ end }}
      data:
      {{- range $val_data := $val_sec.data }}
        - key: {{ $val_data.key | default $val_data.objectName }}
          objectName: {{ $val_data.objectName }}
      {{ end -}}
    {{ end -}}
{{ end -}}
{{ end -}}
