rabbitMQ:
  # legacy repository until move away from bitnami (UN-12358)
  repository: "bitnamilegacy/rabbitmq"
  # With this update rabbitmq requires certain feature flags to be enabled before the update.
  # They should already be enabled from the previous version.
  # 
  # To list all feature flags:
  # rabbitmqctl list_feature_flags
  # 
  # Please make sure you have enabled the following feature flags before the update:
  # - stream_filtering
  # - stream_update_config_command
  # - restart_streams
  # - stream_sac_coordinator_unblock_group
  #
  # To enable a feature flag:
  # rabbitmqctl enable_feature_flag <name>
  #
  # More information here: https://www.rabbitmq.com/docs/feature-flags#core-feature-flags
  versions:
    chart: 16.0.14
    image: 4.1.3-debian-12-r1
  load_definition_policies: "[]"
keda:
  versions:
    chart: 2.12.0
trivyOperator:
  versions:
    chart: 0.15.1