chat:
  _common:
    acr:
      url: uniquecr.azurecr.io
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    env:
      CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.blob.core.windows.net; script-src 'self' 'unsafe-inline' blob:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.unique.app *.core.windows.net wss://*.unique.app; media-src 'self' *.blob.core.windows.net; frame-ancestors 'self'; frame-src 'self' https://*.unique.app;"
    defaultReleases:
      nextChat:             "2026.04.0"
      nextKnowledgeUpload:  "2026.04.0"
      nextTheme:            "2026.04.0"
      nextAdmin:            "2026.04.0"
      nodeChat:             "2026.04.0"
      nodeIngestion:        "2026.04.0"
      nodeIngestionWorker:  "2026.04.0"
      configurationBackend: "2026.04.0"
      nodeScopeManagement:  "2026.04.0"
      backendServiceSpeech: "2026.04.0"
      assistantsCore:       "2026.04.0"
  nextChat:
    env:
      MAX_FILE_SIZE_IN_MB: 512
      MAX_HEAP_MB: 400
      FEATURE_FLAG_NET_PROMOTER_SCORE_UI_UN_7747: "true"
      FILE_TYPES_DOCUMENT_TRANSLATOR: "docx,xlsx,pptx"
      FEATURE_FLAG_ABOUT_SPACE_SECTION_UN_10270: "false"
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "false"
      FEATURE_FLAG_ENABLE_ADVANCED_FORMATTING_UN_9758: "true"
      FEATURE_FLAG_ENABLE_SPACES_2_0_UN_11203: "true" # enable spaces 2.0, BETA feature
      FEATURE_FLAG_ENABLE_MCP_ADMIN_UN_14099: "false" # BETA MCP admin feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MCP_UN_11963: "false" # BETA MCP feature, only enable for DEV/TEST
    resources:
      requests:
        cpu: 300m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 550Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /chat
      paths:
        default:
          enabled: true
        root:
          enabled: true
          redirectPath: /chat
    strategy:
      type: Recreate
  nextKnowledgeUpload:
    env:
      MAX_HEAP_MB: 400
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "false"
      FEATURE_FLAG_ENABLE_CAN_MANAGE_ACCESS_UN_11608: "false"
      FEATURE_FLAG_ENABLE_MCP_ADMIN_UN_14099: "false" # BETA MCP admin feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MCP_UN_11963: "false" # BETA MCP feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_FILE_BASED_ACCESS_UN_12660: "false" # Experimental feature, only enable for DEV/TEST
    resources:
      requests:
        cpu: 300m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 550Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /knowledge-upload
      paths:
        default:
          enabled: true
    strategy:
      type: Recreate
  nextTheme:
    env:
      MAX_HEAP_MB: 400
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "false"
      FEATURE_FLAG_ENABLE_MCP_ADMIN_UN_14099: "false" # BETA MCP admin feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MCP_UN_11963: "false" # BETA MCP feature, only enable for DEV/TEST
    resources:
      requests:
        cpu: 300m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 550Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /theme
      paths:
        default:
          enabled: true
    strategy:
      type: Recreate
  nextAdmin:
    env:
      MAX_HEAP_MB: 400
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "false"
      FEATURE_FLAG_ENABLE_MCP_ADMIN_UN_14099: "false" # BETA MCP admin feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MCP_UN_11963: "false" # BETA MCP feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_SPACES_2_0_UN_11203: "true" # enable spaces 2.0, BETA feature
    resources:
      requests:
        cpu: 300m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 550Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /admin
      paths:
        default:
          enabled: true
    strategy:
      type: Recreate
  nodeChat:
    env:
      PUBSUB_BACKEND: redis
      MAX_HEAP_MB: 4625
      BENCHMARKS_PER_MINUTE_PER_PROCESS: 1
      AMQP_BENCHMARK_PREFETCH: 1
      INTERNAL_MODULES_CONFIG: >- 
        [
        {"name": "SearchInVectorDBV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/search"},
        {"name": "ImageSummarizer", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/image_summarizer"},
        {"name": "TranslationOneToOne", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/translation_one_to_one"},
        {"name": "WebSearch", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/web_search"},
        {"name": "ComplianceCheck", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/compliance_check"},
        {"name": "QuestionExtractor", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_extractor"},
        {"name": "QuestionAnswerer", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_answerer"},
        {"name": "Questionnaire", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_answerer"},
        {"name": "QuestionPredictor", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_predictor"},
        {"name": "DocumentSummarizerV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/document_summarizer"},
        {"name": "ImageUpload", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/image_upload"},
        {"name": "DocumentTranslator", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/document_translator"},
        {"name": "AgenticSearch", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/agentic_search"},
        {"name": "TranslatorV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/translator_v2"},
        {"name": "InvestmentResearch", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/investment_research"},
        {"name": "EarningCallsBeta", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/earning_calls"},
        {"name": "HallucinationLevelEvaluation", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/evaluations/hallucination-level"},
        {"name": "DueDiligence", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/magic_table_dd"},
        {"name": "RfpAgent", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/rfp_agent"},
        {"name": "UniqueAi", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/unique_ai"},
        {"name": "KycReviewAgent", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/kyc_review_agent"}
        ]
      ENABLE_CLIENT_INSIGHT_SHIPPER: "true"
      MIN_NO_OF_MESSAGES_BY_USER_BEFORE_NPS_TRIGGER: "30"
      FEATURE_FLAG_NET_PROMOTER_SCORE_UI_UN_7747: "true"
      APP_REPOSITORY_URL: http://node-app-repository.apps.svc.cluster.local:8088
      ENABLE_DOWNLOAD_UPLOAD_FILES_AS_STREAM: "true"
      ENABLE_UPLOAD_CHAT_INTERACTIONS_AS_STREAM: "true"
      ENABLE_ANALYTICS_CHAT_DETAILED_INTERACTIONS_PRISMA_CURSOR: "true"
      ASSISTANT_CORE_API_URL: http://assistants-core.chat.svc.cluster.local:8081/core
      CHAT_LLM_INITIAL_REQUEST_TIMEOUT: 20000
      FEATURE_FLAG_ENABLE_MCP_ADMIN_UN_14099: "false" # BETA MCP admin feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_MCP_UN_11963: "false" # BETA MCP feature, only enable for DEV/TEST
      MCP_POLICY_MODE: "UNRESTRICTED" # STRICT | PATTERN | UNRESTRICTED
      MCP_ALLOWED_ENDPOINTS: "*" # Examples: *.unique.app, mcp.*.com
      MCP_DENIED_ENDPOINTS: ""
      CACHE_REDIS_DB: 3
    resources:
      requests:
        cpu: 2
        memory: 4750Mi
      limits:
        cpu: 6
        memory: 7.5Gi
    routes:
      hostname: unset_default_value
      pathPrefix: /chat
      paths:
        default:
          enabled: true
        versioned:
          enabled: true
        probe:
          enabled: true
  nodeIngestion:
    env:
      AZURE_OPENAI_API_DEPLOYMENT_NAME: text-embedding-ada-002
      AZURE_OPENAI_API_VERSION: 2023-05-15
      TRUSTED_DOMAINS: '["*.blob.core.windows.net"]'
      USE_SCOPE_MANAGEMENT: "true"
      ZITADEL_ROOT_ORG_ID: ""
      MAX_HEAP_MB: 1536
      ENABLE_MALWARE_SCAN: "true"
      REPLICATION_FACTOR: 2
      FILE_RETENTION_IN_DAYS: 7
      MAX_REQUEST_BODY_SIZE: '30mb'
      PDF_READ_MODE: DOC_INTELLIGENCE_DEFAULT # Uses MDI for ingestion. Unique recommends this as default if MDI is available.
      FEATURE_FLAG_ENABLE_FILE_BASED_ACCESS_UN_12660: "false" # experimental file-based access feature, only enable for DEV/TEST
      FEATURE_FLAG_ENABLE_SEARCH_ADAPTER_ELASTICSEARCH_UN_9883: "true" 
      FEATURE_FLAG_ENABLE_ELASTICSEARCH_INDEXING: "true"
    resources:
      requests:
        cpu: 2
        memory: 2048Mi
      limits:
        cpu: 4
        memory: 2560Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /ingestion
      paths:
        default:
          enabled: true
        scoped:
          enabled: true
        probe:
          enabled: true
  nodeIngestionWorker:
    env:
      MAX_HEAP_MB: 3800
      NUMBER_OF_PDF_PAGES_IN_PARALLEL: 25
      CONVERT_OFFICE_FILES_TO_PDF: "true"
      THREAD_TASK_TIMEOUT_MS: "3600000"
      FEATURE_FLAG_ENABLE_PPT_PAGE_BASED_CHUNKING_UN_9444: "true"
      FEATURE_FLAG_ENABLE_LANDSCAPED_PDF_PAGE_BASED_CHUNKING_UN_10606: "true"
      CUSTOM_API_DEFINITIONS: >-
        [ 
        {"identifier": "Unique Text Extraction API", "url": "http://assistants-core.chat.svc.cluster.local:8081/core/text-extractions"}, 
        {"identifier": "Unique Text and Image Extraction API", "url": "http://assistants-core.chat.svc.cluster.local:8081/core/text-and-image-extractions"}
        ]
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 5Gi
  nodeIngestionWorkerChat:
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 5Gi
  configurationBackend:
    env:
      MAX_HEAP_MB: 384
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1024Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /configuration
      paths:
        default:
          enabled: true
        probe:
          enabled: true
  nodeScopeManagement:
    env:
      MAX_HEAP_MB: 1750
      ENABLE_CLIENT_INSIGHT_SHIPPER: "true"
      SCOPE_MANAGEMENT_IDP_ROLE_MANAGEMENT: "GRANT_AND_REVOKE"
      FEATURE_FLAG_ENABLE_CAN_MANAGE_ACCESS_UN_11608: "false"
      FEATURE_FLAG_ENABLE_FILE_BASED_ACCESS_UN_12660: "false" # experimental file-based access feature, only enable for DEV/TEST
    resources:
      requests:
        cpu: 1
        memory: 1850Mi
      limits:
        cpu: 2
        memory: 2Gi
    routes:
      hostname: unset_default_value
      pathPrefix: /scope-management
      paths:
        default:
          enabled: true
        probe:
          enabled: true
    extraRoutes:
      scim:
        enabled: true
        annotations:
          konghq.com/plugins: unique-route-metrics
        parentRefs:
          - name: kong
            namespace: system
            group: gateway.networking.k8s.io
            kind: Gateway
        hostnames:
          - unset_default_value
        matches:
          - path:
              type: PathPrefix
              value: /scim
      membership-sync:
        enabled: true
        annotations:
          konghq.com/plugins: unique-route-metrics
        parentRefs:
          - name: kong
            namespace: system
            group: gateway.networking.k8s.io
            kind: Gateway
        hostnames:
          - unset_default_value
        matches:
          - path:
              type: PathPrefix
              value: /membership-sync
  backendServiceSpeech:
    env:
      # see here for supported languages:
      # https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=stt
      SPEECH_SUPPORTED_LANGUAGES: "de-CH, en-US, es-ES, pl-PL"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /speech
      paths:
        default:
          enabled: true
        probe:
          enabled: true
  assistantsCore:
    env:
      GUNICORN_WORKERS: 2
      GUNICORN_THREADS: 4
      AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT_DEFINITIONS: []
      AZURE_DOCUMENT_INTELLIGENCE_LOCATION: switzerlandnorth
      AZURE_DOCUMENT_INTELLIGENCE_API_VERSION: 2024-11-30
      TEXT_AND_IMAGE_EXTRACTOR_API_LOCATION: switzerlandnorth
      TEXT_AND_IMAGE_EXTRACTOR_API_VERSION: 2024-11-30
      ENABLED_MIME_TYPES_DOCUMENT_TRANSLATION: '["DOCX", "MSEXCEL", "EXCEL", "PPT", "MSPPT"]'
      GOOGLE_SEARCH_API_ENDPOINT: https://customsearch.googleapis.com/customsearch/v1
      GOOGLE_SEARCH_ENGINE_ID: unset_default_value
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 2
        memory: 6Gi
qdrant:
  chart:
    version: 1.15.5
  imageTag: v1.15.1
  resources:
    requests:
      cpu: 200m
      memory: 8Gi
    limits:
      memory: 8Gi
  persistence:
    size: 100Gi
  probes:
    startup:
      periodSeconds: 30
zitadel:
  replicaCount: 2
  versions:
    chart: 8.13.1
    image: v3.4.0
  resources:
    requests:
      cpu: 1
      memory: 1500Mi
    limits:
      cpu: 1
      memory: 1500Mi
keda:
  nodeIngestionWorker:
    minReplicaCount: 1
    maxReplicaCount: 6
    # Set cron to null to disable cron-based scaling, or configure with values to enable
    cron: null
  nodeIngestionWorkerChat:
    minReplicaCount: 1
    maxReplicaCount: 6
    cron:
      timezone: Europe/Zurich
      start: 0 7 * * 1-5
      end: 0 19 * * 1-5
      desiredReplicas: "2" # scale up more according to your need
elasticsearch:
  ingestion:
    nodeSets:
      count: 3  # In production, run cluster with 3 nodes, can be set to 1 for development envs