chat:
  _common:
    acr:
      url: uniquecr.azurecr.io
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    ingressDefaults:
      enabled: true
      tls:
        enabled: true
      className: azure-application-gateway
      annotations:
        appgw.ingress.kubernetes.io/ssl-redirect: "true"
        appgw.ingress.kubernetes.io/rewrite-rule-set: security-headers
        appgw.ingress.kubernetes.io/request-timeout: "120" # 120 is our sane cap, anyone wanting more than this must provide evidence that their implementation is cleanly engineered
        cert-manager.io/cluster-issuer: letsencrypt
    env:
      CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.blob.core.windows.net; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.unique.app *.core.windows.net wss://*.unique.app; media-src 'self' *.blob.core.windows.net; frame-ancestors 'self'; frame-src 'self' https://*.unique.app;"
    defaultReleases:
      nextChat:            2024.40
      nextKnowledgeUpload: 2024.40
      nextTheme:           2024.40
      nextAdmin:           2024.40
      nodeChat:            2024.40
      nodeIngestion:       2024.40
      nodeIngestionWorker: 2024.40
      nodeTheme:           2024.40
      nodeScopeManagement: 2024.40
      assistantsCore:      2024.40
  _rootIngress:
    enabled: true
  nextChat:
    env:
      MAX_HEAP_MB: 400
      FEATURE_FLAG_NEW_TRANSLATION_UI_UN_7233: "true"
      FEATURE_FLAG_STOP_STREAMING_UN_4824: "true"
      FEATURE_FLAG_NET_PROMOTER_SCORE_UI_UN_7747: "true"
    resources:
      requests:
        cpu: 300m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 550Mi
    replicaCount: 2
    strategy:
      type: Recreate
  nextKnowledgeUpload:
    env:
      MAX_HEAP_MB: 350
      FEATURE_FLAG_NEW_KNOWLEDGE_BASE_UN_5652: "true"
      FEATURE_FLAG_ENABLE_SPACE_FOLDER_UN_7028: ""
    resources:
      requests:
        cpu: 300m
        memory: 450Mi
      limits:
        cpu: 300m
        memory: 500Mi
    replicaCount: 2
    strategy:
      type: Recreate
  nextTheme:
    env:
      MAX_HEAP_MB: 200
      UNIQUE_THEME: {"color-primary-cta": "#a04044", "color-primary-variant": "#90393c", "color-secondary": "#5b5b5b", "color-secondary-variant": "#3e3e3e", "color-background": "#f6f6f6", "color-background-variant": "#ececec", "color-surface": "#ffffff", "color-control": "#cfcfcf", "color-info": "#4167a6", "color-success-light": "#ebfaf2", "color-success-dark": "#0f9451", "color-error-light": "#cc5e71", "color-error-dark": "#d12a46", "color-attention": "#db7600", "color-attention-variant": "#8d4c82", "color-on-primary": "#ffffff", "color-on-secondary": "#ffffff", "color-on-background-main": "#3e3e3e", "color-on-background-dimmed": "#787878", "color-on-surface": "#3e3e3e", "color-on-control-main": "#3e3e3e", "color-on-control-dimmed": "#b3b3b3", "color-on-info": "#ffffff", "color-on-success-light": "#3e3e3e", "color-on-success-dark": "#ffffff", "color-on-error-light": "#ffffff", "color-on-error-dark": "#ffffff", "color-on-attention": "#ffffff", "color-on-attention-variant": "#ffffff"}
      UNIQUE_BACKGROUND_COLOR: F6F6F6
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 100m
        memory: 350Mi
    replicaCount: 2
    strategy:
      type: Recreate
  nextAdmin:
    env:
      MAX_HEAP_MB: 350
      FEATURE_FLAG_NEW_TRANSLATION_UI_UN_7233: true
      FEATURE_FLAG_ENABLE_SPACE_FOLDER_UN_7028: ""
      FEATURE_FLAG_KNOWLEDGE_SCOPE_UN_5773: ""
    resources:
      requests:
        cpu: 300m
        memory: 450Mi
      limits:
        cpu: 300m
        memory: 500Mi
    replicaCount: 2
    strategy:
      type: Recreate
  nodeChat:
    env:
      PUBSUB_BACKEND: redis
      MAX_HEAP_MB: 450
      BENCHMARKS_PER_MINUTE_PER_PROCESS: 1
      AMQP_BENCHMARK_PREFETCH: 1
      INTERNAL_MODULES_CONFIG: >- 
        [
        {"name": "SearchInVectorDBV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/search"}, 
        {"name": "ImageSummarizer", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/image_summarizer"}, 
        {"name": "TranslationOneToOne", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/translation_one_to_one"}, 
        {"name": "WebSearch", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/web_search"}, 
        {"name": "ComplianceCheck", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/compliance_check"}, 
        {"name": "QuestionExtractor", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_extractor"}, 
        {"name": "QuestionAnswerer", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_answerer"}, 
        {"name": "QuestionPredictor", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_predictor"}, 
        {"name": "DocumentSummarizerV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/document_summarizer"},
        {"name": "ImageUpload", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/image_upload"}
        ]
      ENABLE_CLIENT_INSIGHT_SHIPPER: "false"
      MIN_NO_OF_MESSAGES_BY_USER_BEFORE_NPS_TRIGGER: '30'
    serviceAccount: {}
    resources:
      requests:
        cpu: 500m
        memory: 550Mi
      limits:
        cpu: 500m
        memory: 600Mi
    tyk:
      rateLimit:
        per: 60
        rate: 4096
        quotaMax: -1
      hardTimeouts: []
      exposePublicApi:
        enabled: true
        hardTimeouts:
          - path: "/openai/chat/{:path}"
            method: "POST"
            timeoutSeconds: 600
          - path: "/integrated/chat/{:path}"
            method: "POST"
            timeoutSeconds: 600
  nodeIngestion:
    env:
      AZURE_OPENAI_API_DEPLOYMENT_NAME: text-embedding-ada-002
      AZURE_OPENAI_API_VERSION: 2023-05-15
      TRUSTED_DOMAINS: '["*.blob.core.windows.net"]'
      USE_SCOPE_MANAGEMENT: "true"
      ZITADEL_ROOT_ORG_ID: ""
      MAX_HEAP_MB: 550
      ENABLE_MALWARE_SCAN: "false"
      REPLICATION_FACTOR: 2
      FILE_RETENTION_IN_DAYS: 0
      FF_UN7111_UPLOAD_THROUGH_BACKEND: "true"
      RERANKER_CONFIGURATION: '[{"deploymentName": "crossencoder_reranker", "apiUrl": "http://assistants-reranker.chat.svc.cluster.local:8081/reranker/rerank"}]'
    tyk:
      rateLimit:
        rate: 4096
        quotaMax: -1
      scopedApi:
        enabled: true
        hardTimeouts:
          - path: "/upload"
            method: "PUT"
            timeoutSeconds: 600 # for large files and bad connections during upload
    serviceAccount: {}
    resources:
      requests:
        cpu: 200m
        memory: 650Mi
      limits:
        cpu: 200m
        memory: 700Mi
  nodeIngestionWorker:
    env:
      MAX_HEAP_MB: 850
    serviceAccount: {}
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1050Mi
  nodeTheme:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 100m
        memory: 350Mi
    tyk:
      rateLimit:
        rate: 4096
        quotaMax: -1
  nodeScopeManagement:
    env:
      MAX_HEAP_MB: 750
      ENABLE_CLIENT_INSIGHT_SHIPPER: "false"
    tyk:
      rateLimit:
        rate: 4096
        quotaMax: -1
    resources:
      requests:
        cpu: 500m
        memory: 850Mi
      limits:
        cpu: 1
        memory: 900Mi
  assistantsCore:
    env:
      GUNICORN_WORKERS: 2
      GUNICORN_THREADS: 4
    resources:
      requests:
        cpu: 500m
        memory: 550Mi
      limits:
        cpu: 500m
        memory: 600Mi
qdrant:
  chart:
    version: 0.7.3
  imageTag: v1.8.4
  resources:
    requests:
      cpu: 100m
      memory: 1.8Gi
    limits:
      memory: 2Gi
  persistence:
    size: 10Gi
  probes:
    startup:
      periodSeconds: 30
zitadel:
  replicaCount: 2
  versions:
    chart: 8.1.0
    image: v2.62.1
  resources:
    requests:
      cpu: 1
      memory: 1500Mi
    limits:
      cpu: 1
      memory: 1500Mi
tyk:
  agicRequestTimeout: 600 # 10 minutes to allow long-running LLM requests.
  proxyDefaultTimeout: 600 # 10 minutes to allow long-running LLM requests.
  replicaCount: 2
  gateway:
    resources:
      limits:
          cpu: 80m
          memory: 250Mi
      requests:
          cpu: 80m
          memory: 250Mi
eventBasedAutoscaling:
  nodeIngestionWorker:
    minReplicaCount: 0
    maxReplicaCount: 6
  nodeIngestionWorkerChat:
    minReplicaCount: 0
    maxReplicaCount: 6