chat:
  _common:
    acr:
      url: uniquecr.azurecr.io
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    ingressDefaults:
      enabled: true
      tls:
        enabled: true
      className: azure-application-gateway
      annotations:
        appgw.ingress.kubernetes.io/ssl-redirect: "true"
        appgw.ingress.kubernetes.io/rewrite-rule-set: security-headers
        appgw.ingress.kubernetes.io/request-timeout: "120" # 120 is our sane cap, anyone wanting more than this must provide evidence that their implementation is cleanly engineered
        cert-manager.io/cluster-issuer: letsencrypt
    env:
      CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.blob.core.windows.net; script-src 'self' 'unsafe-inline' blob:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.unique.app *.core.windows.net wss://*.unique.app; media-src 'self' *.blob.core.windows.net; frame-ancestors 'self'; frame-src 'self' https://*.unique.app;"
    defaultReleases:
      nextChat:             "2025.28"
      nextKnowledgeUpload:  "2025.28"
      nextTheme:            "2025.28"
      nextAdmin:            "2025.28"
      nodeChat:             "2025.28"
      nodeIngestion:        "2025.28"
      nodeIngestionWorker:  "2025.28"
      configurationBackend: "2025.28"
      nodeScopeManagement:  "2025.28"
      backendServiceSpeech: "2025.28"
      assistantsCore:       "2025.28"
  nextChat:
    env:
      MAX_FILE_SIZE_IN_MB: 200
      MAX_HEAP_MB: 400
      FEATURE_FLAG_NET_PROMOTER_SCORE_UI_UN_7747: "true"
      FILE_TYPES_DOCUMENT_TRANSLATOR: "docx,xlsx,pptx"
      FEATURE_FLAG_ABOUT_SPACE_SECTION_UN_10270: "false"
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "true"
    resources:
      requests:
        cpu: 300m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 550Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /chat
      paths:
        default:
          enabled: true
        root:
          enabled: true
          redirectPath: /chat
    strategy:
      type: Recreate
  nextKnowledgeUpload:
    env:
      MAX_HEAP_MB: 350
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "true"
      FEATURE_FLAG_ENABLE_CAN_MANAGE_ACCESS_UN_11608: "true"
    resources:
      requests:
        cpu: 300m
        memory: 450Mi
      limits:
        cpu: 300m
        memory: 500Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /knowledge-upload
      paths:
        default:
          enabled: true
    strategy:
      type: Recreate
  nextTheme:
    env:
      MAX_HEAP_MB: 200
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "true"
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 100m
        memory: 350Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /theme
      paths:
        default:
          enabled: true
    strategy:
      type: Recreate
  nextAdmin:
    env:
      MAX_HEAP_MB: 350
      FEATURE_FLAG_USER_API_KEY_GENERATION_UN_11416: "true"
    resources:
      requests:
        cpu: 300m
        memory: 450Mi
      limits:
        cpu: 300m
        memory: 500Mi
    replicaCount: 2
    routes:
      hostname: unset_default_value
      pathPrefix: /admin
      paths:
        default:
          enabled: true
    strategy:
      type: Recreate
  nodeChat:
    env:
      PUBSUB_BACKEND: redis
      MAX_HEAP_MB: 450
      BENCHMARKS_PER_MINUTE_PER_PROCESS: 1
      AMQP_BENCHMARK_PREFETCH: 1
      INTERNAL_MODULES_CONFIG: >- 
        [
        {"name": "SearchInVectorDBV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/search"},
        {"name": "ImageSummarizer", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/image_summarizer"},
        {"name": "TranslationOneToOne", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/translation_one_to_one"},
        {"name": "WebSearch", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/web_search"},
        {"name": "ComplianceCheck", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/compliance_check"},
        {"name": "QuestionExtractor", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_extractor"},
        {"name": "QuestionAnswerer", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_answerer"},
        {"name": "Questionnaire", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_answerer"},
        {"name": "QuestionPredictor", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/question_predictor"},
        {"name": "DocumentSummarizerV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/document_summarizer"},
        {"name": "ImageUpload", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/image_upload"},
        {"name": "DocumentTranslator", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/document_translator"},
        {"name": "AgenticSearch", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/agentic_search"},
        {"name": "TranslatorV2", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/translator_v2"},
        {"name": "InvestmentResearch", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/investment_research"},
        {"name": "EarningCallsBeta", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/earning_calls"},
        {"name": "HallucinationLevelEvaluation", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/evaluations/hallucination-level"},
        {"name": "DueDiligence", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/magic_table_dd"},
        {"name": "RfpAgent", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/rfp_agent"},
        {"name": "UniqueAi", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/unique_ai"},
        {"name": "KycReviewAgent", "apiURL": "http://assistants-core.chat.svc.cluster.local:8081/core/kyc_review_agent"}
        ]
      ENABLE_CLIENT_INSIGHT_SHIPPER: "false"
      MIN_NO_OF_MESSAGES_BY_USER_BEFORE_NPS_TRIGGER: "30"
      FEATURE_FLAG_NET_PROMOTER_SCORE_UI_UN_7747: "true"
      APP_REPOSITORY_URL: http://node-app-repository.apps.svc.cluster.local:8088
      ENABLE_DOWNLOAD_UPLOAD_FILES_AS_STREAM: "true"
      ENABLE_UPLOAD_CHAT_INTERACTIONS_AS_STREAM: "true"
      ENABLE_ANALYTICS_CHAT_DETAILED_INTERACTIONS_PRISMA_CURSOR: "true"
    resources:
      requests:
        cpu: 500m
        memory: 950Mi
      limits:
        cpu: 500m
        memory: 1000Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /chat
      paths:
        default:
          enabled: true
        versioned:
          enabled: true
        probe:
          enabled: true
  nodeIngestion:
    env:
      AZURE_OPENAI_API_DEPLOYMENT_NAME: text-embedding-ada-002
      AZURE_OPENAI_API_VERSION: 2023-05-15
      TRUSTED_DOMAINS: '["*.blob.core.windows.net"]'
      USE_SCOPE_MANAGEMENT: "true"
      ZITADEL_ROOT_ORG_ID: ""
      MAX_HEAP_MB: 550
      ENABLE_MALWARE_SCAN: "true"
      REPLICATION_FACTOR: 2
      FILE_RETENTION_IN_DAYS: 0
      RERANKER_CONFIGURATION: '[{"deploymentName": "crossencoder_reranker", "apiUrl": "http://assistants-reranker.chat.svc.cluster.local:8081/reranker/rerank"}]'
      MAX_REQUEST_BODY_SIZE: '30mb'
      PDF_READ_MODE: DOC_INTELLIGENCE_DEFAULT # Uses MDI for ingestion. Unique recommends this as default if MDI is available.
    resources:
      requests:
        cpu: 200m
        memory: 650Mi
      limits:
        cpu: 200m
        memory: 700Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /ingestion
      paths:
        default:
          enabled: true
        scoped:
          enabled: true
        probe:
          enabled: true
  nodeIngestionWorker:
    env:
      MAX_HEAP_MB: 850
      CONVERT_OFFICE_FILES_TO_PDF: "true"
      FEATURE_FLAG_ENABLE_PPT_PAGE_BASED_CHUNKING_UN_9444: "true"
      FEATURE_FLAG_ENABLE_LANDSCAPED_PDF_PAGE_BASED_CHUNKING_UN_10606: "true"
      CUSTOM_API_DEFINITIONS: >-
        [ 
        {"identifier": "Unique Text Extraction API", "url": "http://assistants-core.chat.svc.cluster.local:8081/core/text-extractions"} 
        ]
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1050Mi
  nodeIngestionWorkerChat:
    resources:
      requests:
        cpu: 1.5
        memory: 1Gi
      limits:
        cpu: 1.5
        memory: 1Gi
  configurationBackend:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 100m
        memory: 350Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /configuration
      paths:
        default:
          enabled: true
        probe:
          enabled: true
  nodeScopeManagement:
    env:
      MAX_HEAP_MB: 750
      ENABLE_CLIENT_INSIGHT_SHIPPER: "false"
      FEATURE_FLAG_ENABLE_CAN_MANAGE_ACCESS_UN_11608: "true"
    resources:
      requests:
        cpu: 500m
        memory: 850Mi
      limits:
        cpu: 1
        memory: 900Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /scope-management
      paths:
        default:
          enabled: true
        probe:
          enabled: true
    extraRoutes:
      scim:
        enabled: true
        annotations:
          konghq.com/plugins: unique-route-metrics
        parentRefs:
          - name: kong
            namespace: system
            group: gateway.networking.k8s.io
            kind: Gateway
        hostnames:
          - unset_default_value
        matches:
          - path:
              type: PathPrefix
              value: /scim
      membership-sync:
        enabled: true
        annotations:
          konghq.com/plugins: unique-route-metrics
        parentRefs:
          - name: kong
            namespace: system
            group: gateway.networking.k8s.io
            kind: Gateway
        hostnames:
          - unset_default_value
        matches:
          - path:
              type: PathPrefix
              value: /membership-sync
  backendServiceSpeech:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /speech
      paths:
        default:
          enabled: true
        probe:
          enabled: true
  assistantsCore:
    env:
      GUNICORN_WORKERS: 2
      GUNICORN_THREADS: 4
      AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT_DEFINITIONS: []
      AZURE_DOCUMENT_INTELLIGENCE_LOCATION: switzerlandnorth
      AZURE_DOCUMENT_INTELLIGENCE_API_VERSION: 2023-07-31
      ENABLED_MIME_TYPES_DOCUMENT_TRANSLATION: '["DOCX", "MSEXCEL", "EXCEL", "PPT", "MSPPT"]'
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 4Gi
qdrant:
  chart:
    version: 0.7.3
  imageTag: v1.8.4
  resources:
    requests:
      cpu: 100m
      memory: 3.6Gi
    limits:
      memory: 4Gi
  persistence:
    size: 10Gi
  probes:
    startup:
      periodSeconds: 30
zitadel:
  replicaCount: 2
  versions:
    chart: 8.1.0
    image: v2.63.9
  resources:
    requests:
      cpu: 1
      memory: 1500Mi
    limits:
      cpu: 1
      memory: 1500Mi
eventBasedAutoscaling:
  nodeIngestionWorker:
    minReplicaCount: 0
    maxReplicaCount: 6
  nodeIngestionWorkerChat:
    minReplicaCount: 0
    maxReplicaCount: 6