appRepo:
  _common:
    acr: 
      url: uniqueapp.azurecr.io
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    defaultReleases:
      nodeAppRepository:    image-tag-from-release-notes
      nodeWebhookWorker:    image-tag-from-release-notes
      nodeWebhookScheduler: image-tag-from-release-notes
  nodeAppRepository:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        # If you change this, also change --max-old-space-size= in the Dockerfile!
        memory: 350Mi
    tyk:
      rateLimit:
        rate: 4096
        quotaMax: -1
    secrets:
      AZURE_SUBSCRIPTION_ID: # must be provided empty so template does not fail
      AZURE_RESOURCE_GROUP: # must be provided empty so template does not fail
      APP_LOGS_STORAGE_ACCOUNT: # must be provided empty so template does not fail
    serviceAccount:
      enabled: false
      workloadIdentity:
        enabled: false
        clientId: # must be provided empty so template does not fail
  nodeWebhookScheduler:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        memory: 350Mi
  nodeWebhookWorker:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        memory: 350Mi