appRepo:
  _common:
    acr: 
      url: uniquecr.azurecr.io
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    defaultReleases:
      nodeAppRepository:            "2026.04.0"
      nodeWebhookWorker:            "2026.04.0"
      nodeWebhookScheduler:         "2026.04.0"
      typescriptServiceEventSocket: "2026.04.0"
      clientInsightsExporter:       "2026.04.0"
  nodeAppRepository:
    env:
      MAX_HEAP_MB: 1900
    resources:
      requests:
        cpu: 1
        memory: 2000Mi
      limits:
        cpu: 2
        memory: 2048Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /apps
      paths:
        default:
          enabled: true
        probe:
          enabled: true
    serviceAccount:
      enabled: false
      workloadIdentity:
        enabled: false
        clientId: # must be provided empty so template does not fail
  nodeWebhookScheduler:
    env:
      MAX_HEAP_MB: 384
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 640Mi
  nodeWebhookWorker:
    env:
      MAX_HEAP_MB: 384
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 640Mi
  typescriptServiceEventSocket:
    env:
      MAX_HEAP_MB: 384
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 640Mi
    routes:
      hostname: unset_default_value
      pathPrefix: /event-socket 
      paths:
        versioned:
          enabled: true
        probe:
          enabled: true
  clientInsightsExporter:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        memory: 350Mi
    cronJob:
      enabled: false