appRepo:
  _common:
    acr: 
      url: uniquecr.azurecr.io
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    defaultReleases:
      nodeAppRepository:            "2025.02"
      nodeWebhookWorker:            "2025.02"
      nodeWebhookScheduler:         "2025.02"
      typescriptServiceEventSocket: "2025.02"
      clientInsightsExporter:       "2025.02"
  nodeAppRepository:
    env:
      MAX_HEAP_MB: 750
    resources:
      requests:
        cpu: 500m
        memory: 850Mi
      limits:
        memory: 900Mi
    tyk:
      rateLimit:
        rate: 4096
        quotaMax: -1
    secrets:
      AZURE_SUBSCRIPTION_ID: # must be provided empty so template does not fail
      AZURE_RESOURCE_GROUP: # must be provided empty so template does not fail
      APP_LOGS_STORAGE_ACCOUNT: # must be provided empty so template does not fail
    serviceAccount:
      enabled: false
      workloadIdentity:
        enabled: false
        clientId: # must be provided empty so template does not fail
  nodeWebhookScheduler:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        memory: 350Mi
  nodeWebhookWorker:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        memory: 350Mi
  typescriptServiceEventSocket:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        memory: 350Mi
    tyk:
      exposePublicApi:
        enabled: true
        hardTimeouts:
          - path: "/events/stream" # Increase timeout for EventSource connections
            method: "GET"
            timeoutSeconds: 600 # 10 minutes
  clientInsightsExporter:
    env:
      MAX_HEAP_MB: 200
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 200m
        memory: 350Mi
    cronJob:
      enabled: false