confluenceConnector:
  defaultReleases:
    confluenceConnector: sha-3863569
  replicaCount: 1
  env:
    CONFLUENCE_TOKENS_PER_MINUTE: 250
    CONFLUENCE_URL: https://your-confluence-url
    INGEST_SINGLE_LABEL: ai-ingest
    INGEST_ALL_LABEL: ai-ingest-all
    TEST_MODE: true
  livenessProbe:
    httpGet:
      path: /health
      port: 8083
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
      port: 8083
    initialDelaySeconds: 30
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /health
      port: 8083
    initialDelaySeconds: 30
    periodSeconds: 10