{{- $fullName := include "common.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
    {{- toYaml .Values.rollingUpdate | nindent 6 }}
    {{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/deployment-env: {{ include (print $.Chart.Name "/templates/deployment-env.yaml") . | sha256sum | trunc 8 | quote }}
        {{- if .Values.envSecrets }}
        checksum/secrets: {{ include (print $.Chart.Name "/templates/secrets.yaml") . | sha256sum | trunc 8 | quote }}
        {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        {{- if .Values.secretProvider }}
        aadpodidbinding: {{ default "keyvault" (.Values.secretProvider).aadPodIdBinding }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.probes.enabled }}
          {{- if .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.startup }}
          startupProbe:
            {{- toYaml .Values.probes.startup | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}-env
            {{- if .Values.envSecrets }}
            - secretRef:
                name: {{ $fullName }}-secrets
            {{- end }}
            {{- if .Values.extraEnvCM }}
            {{- range $v := .Values.extraEnvCM }}
            - configMapRef:
                name: {{ $v }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraEnvSecrets }}
            {{- range $v := .Values.extraEnvSecrets }}
            - secretRef:
                name: {{ $v }}
            {{- end }}
            {{- end }}
          env:
            {{- if .Values.secretProvider }}
            {{- range $k, $v := .Values.secretProvider.vaults }}
            {{- range $key, $value := $v }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-{{ $k }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- if .Values.secretProvider }}
          volumeMounts:
          {{- range $k, $v := .Values.secretProvider.vaults }}
            - name: {{ $fullName }}-{{ $k }}
              mountPath: "/mnt/{{ $fullName }}-{{ $k }}"
              readOnly: true
          {{- end }}
          {{- end }}
        {{- if .Values.secretProvider }}
      volumes:
      {{- range $k, $v := .Values.secretProvider.vaults }}
        - name: {{ $fullName }}-{{ $k }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $fullName }}-{{ $k }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
