{{- if .Values.secretProvider }}
{{- $tenantId := .Values.secretProvider.tenantId | required ".Values.secretProvider.tenantId is required." -}}
{{- $fullName := include "common.fullname" . -}}
{{- $labels := include "common.labels" . -}}
{{- range $k, $v := .Values.secretProvider.vaults }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $fullName }}-{{ $k }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ $fullName }}-{{ $k }}
      labels:
        {{- $labels | nindent 8 }}
      data:
        {{- range $value := $v }}
        - key: {{ $value }}
          objectName: {{ $value }}
        {{- end }}
      type: Opaque
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ $k }}
    objects:  |
      array:
        {{- range $value := $v }}
        - |
          objectName: {{ $value }}
          objectType: secret
        {{- end }}
    tenantId: {{ $tenantId }}
{{- end }}
{{- end }}